[build]
  base = "webapp/"
  publish = "build/"
  command = "CI=false npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 